// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Yashil.Common.Core.Interfaces;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Yashil.Core.Entities
{
[Table("AccessLevel", Schema = "base")]
    public partial class AccessLevel : IBaseEntity<int>
    {
        public AccessLevel()
        {
            DashboardStore = new HashSet<DashboardStore>();
            ReportStore = new HashSet<ReportStore>();
            User = new HashSet<User>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(150)]
        public string Title { get; set; }
        public int LevelValue { get; set; }
        public string Description { get; set; }
        public int CreateBy { get; set; }
        public int? ModifyBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreationDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        public bool Deleted { get; set; }
        public int CreatorOrganizationId { get; set; }

        [ForeignKey("CreateBy")]
        [InverseProperty("AccessLevelCreateByNavigation")]
        public virtual User CreateByNavigation { get; set; }
        [ForeignKey("CreatorOrganizationId")]
        [InverseProperty("AccessLevel")]
        public virtual Organization CreatorOrganization { get; set; }
        [ForeignKey("ModifyBy")]
        [InverseProperty("AccessLevelModifyByNavigation")]
        public virtual User ModifyByNavigation { get; set; }
        [InverseProperty("AccessLevel")]
        public virtual ICollection<DashboardStore> DashboardStore { get; set; }
        [InverseProperty("AccessLevel")]
        public virtual ICollection<ReportStore> ReportStore { get; set; }
        [InverseProperty("AccessLevel")]
        public virtual ICollection<User> User { get; set; }
    }
    }