// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Yashil.Common.Core.Interfaces;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Yashil.Core.Entities
{
[Table("AppAction", Schema = "um")]
    public partial class AppAction : IBaseEntity<int>
    {
        public AppAction()
        {
            ResourceAppAction = new HashSet<ResourceAppAction>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(300)]
        public string Title { get; set; }
        public string Description { get; set; }
        public bool SystemAction { get; set; }
        public int CreateBy { get; set; }
        public int? ModifyBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreationDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        public int? ApplicationId { get; set; }
        public bool Deleted { get; set; }

        [ForeignKey("ApplicationId")]
        [InverseProperty("AppAction")]
        public virtual Application Application { get; set; }
        [ForeignKey("CreateBy")]
        [InverseProperty("AppActionCreateByNavigation")]
        public virtual User CreateByNavigation { get; set; }
        [ForeignKey("ModifyBy")]
        [InverseProperty("AppActionModifyByNavigation")]
        public virtual User ModifyByNavigation { get; set; }
        [InverseProperty("AppAction")]
        public virtual ICollection<ResourceAppAction> ResourceAppAction { get; set; }
    }
    }