// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Yashil.Common.Core.Interfaces;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Yashil.Core.Entities
{
[Table("DashboardGroupDashboard", Schema = "dash")]
    public partial class DashboardGroupDashboard : IBaseEntity<int>
    {
        [Key]
        public int Id { get; set; }
        public int CreateBy { get; set; }
        public int? ModifyBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreationDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        public int DashboardStoreId { get; set; }
        public int DashboardGroupId { get; set; }
        public bool Deleted { get; set; }

        [ForeignKey("CreateBy")]
        [InverseProperty("DashboardGroupDashboardCreateByNavigation")]
        public virtual User CreateByNavigation { get; set; }
        [ForeignKey("DashboardGroupId")]
        [InverseProperty("DashboardGroupDashboard")]
        public virtual DashboardGroup DashboardGroup { get; set; }
        [ForeignKey("DashboardStoreId")]
        [InverseProperty("DashboardGroupDashboard")]
        public virtual DashboardStore DashboardStore { get; set; }
        [ForeignKey("ModifyBy")]
        [InverseProperty("DashboardGroupDashboardModifyByNavigation")]
        public virtual User ModifyByNavigation { get; set; }
    }
    }