// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Yashil.Common.Core.Interfaces;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Yashil.Core.Entities
{
[Table("DashboardGroup", Schema = "dash")]
    public partial class DashboardGroup : IBaseEntity<int>
    {
        public DashboardGroup()
        {
            DashboardGroupDashboard = new HashSet<DashboardGroupDashboard>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(200)]
        public string Title { get; set; }
        [Required]
        [StringLength(200)]
        public string EnglishTitle { get; set; }
        public string Description { get; set; }
        public int CreateBy { get; set; }
        public int? ModifyBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreationDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        public int ApplicationId { get; set; }
        public bool Deleted { get; set; }

        [InverseProperty("DashboardGroup")]
        public virtual ICollection<DashboardGroupDashboard> DashboardGroupDashboard { get; set; }
    }
    }