// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Yashil.Common.Core.Interfaces;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Yashil.Core.Entities
{
[Table("Organization", Schema = "um")]
    public partial class Organization : IBaseEntity<int>
    {
        public Organization()
        {
            InverseParent = new HashSet<Organization>();
            User = new HashSet<User>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(300)]
        public string Title { get; set; }
        public string Description { get; set; }
        [Required]
        public bool? IsActive { get; set; }
        public int? ParentId { get; set; }
        public long? UniqueId { get; set; }
        public string CodePath { get; set; }
        public int? Type { get; set; }
        public int? ProvinceId { get; set; }
        public int CreateBy { get; set; }
        public int? ModifyBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreationDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        public int? ApplicationId { get; set; }
        public bool Deleted { get; set; }

        [ForeignKey("ApplicationId")]
        [InverseProperty("Organization")]
        public virtual Application Application { get; set; }
        [ForeignKey("CreateBy")]
        [InverseProperty("OrganizationCreateByNavigation")]
        public virtual User CreateByNavigation { get; set; }
        [ForeignKey("ModifyBy")]
        [InverseProperty("OrganizationModifyByNavigation")]
        public virtual User ModifyByNavigation { get; set; }
        [ForeignKey("ParentId")]
        [InverseProperty("InverseParent")]
        public virtual Organization Parent { get; set; }
        [InverseProperty("Parent")]
        public virtual ICollection<Organization> InverseParent { get; set; }
        [InverseProperty("Organization")]
        public virtual ICollection<User> User { get; set; }
    }
    }