// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Yashil.Common.Core.Interfaces;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Yashil.Core.Entities
{
[Table("Organization", Schema = "um")]
    public partial class Organization : IBaseEntity<int>, IApplicationBasedEntity
    {
        public Organization()
        {
            AccessLevel = new HashSet<AccessLevel>();
            AppConfig = new HashSet<AppConfig>();
            DashboardGroup = new HashSet<DashboardGroup>();
            DashboardStore = new HashSet<DashboardStore>();
            InverseParent = new HashSet<Organization>();
            ReportGroup = new HashSet<ReportGroup>();
            ReportStore = new HashSet<ReportStore>();
            Role = new HashSet<Role>();
            UserCreatorOrganization = new HashSet<User>();
            UserOrganization = new HashSet<User>();
            YashilConnectionString = new HashSet<YashilConnectionString>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(300)]
        public string Title { get; set; }
        public string Description { get; set; }
        [Required]
        public bool? IsActive { get; set; }
        public int? ParentId { get; set; }
        public long? UniqueId { get; set; }
        public string CodePath { get; set; }
        public int? Type { get; set; }
        public int? ProvinceId { get; set; }
        public int CreateBy { get; set; }
        public int? ModifyBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreationDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        public int ApplicationId { get; set; }
        public bool Deleted { get; set; }
        public int CreatorOrganizationId { get; set; }

        [ForeignKey("ApplicationId")]
        [InverseProperty("Organization")]
        public virtual Application Application { get; set; }
        [ForeignKey("CreateBy")]
        [InverseProperty("OrganizationCreateByNavigation")]
        public virtual User CreateByNavigation { get; set; }
        [ForeignKey("ModifyBy")]
        [InverseProperty("OrganizationModifyByNavigation")]
        public virtual User ModifyByNavigation { get; set; }
        [ForeignKey("ParentId")]
        [InverseProperty("InverseParent")]
        public virtual Organization Parent { get; set; }
        [InverseProperty("CreatorOrganization")]
        public virtual ICollection<AccessLevel> AccessLevel { get; set; }
        [InverseProperty("CreatorOrganization")]
        public virtual ICollection<AppConfig> AppConfig { get; set; }
        [InverseProperty("CreatorOrganization")]
        public virtual ICollection<DashboardGroup> DashboardGroup { get; set; }
        [InverseProperty("CreatorOrganization")]
        public virtual ICollection<DashboardStore> DashboardStore { get; set; }
        [InverseProperty("Parent")]
        public virtual ICollection<Organization> InverseParent { get; set; }
        [InverseProperty("CreatorOrganization")]
        public virtual ICollection<ReportGroup> ReportGroup { get; set; }
        [InverseProperty("CreatorOrganization")]
        public virtual ICollection<ReportStore> ReportStore { get; set; }
        [InverseProperty("CreatorOrganization")]
        public virtual ICollection<Role> Role { get; set; }
        [InverseProperty("CreatorOrganization")]
        public virtual ICollection<User> UserCreatorOrganization { get; set; }
        [InverseProperty("Organization")]
        public virtual ICollection<User> UserOrganization { get; set; }
        [InverseProperty("CreatorOrganization")]
        public virtual ICollection<YashilConnectionString> YashilConnectionString { get; set; }
    }
    }