// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Yashil.Common.Core.Interfaces;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Yashil.Core.Entities
{
[Table("ReportGroupReport", Schema = "rpt")]
    public partial class ReportGroupReport : IBaseEntity<int>
    {
        [Key]
        public int Id { get; set; }
        public int CreateBy { get; set; }
        public int? ModifyBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreationDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        public int ReportStoreId { get; set; }
        public int ReportGroupId { get; set; }
        public bool Deleted { get; set; }

        [ForeignKey("CreateBy")]
        [InverseProperty("ReportGroupReportCreateByNavigation")]
        public virtual User CreateByNavigation { get; set; }
        [ForeignKey("ModifyBy")]
        [InverseProperty("ReportGroupReportModifyByNavigation")]
        public virtual User ModifyByNavigation { get; set; }
        [ForeignKey("ReportGroupId")]
        [InverseProperty("ReportGroupReport")]
        public virtual ReportGroup ReportGroup { get; set; }
        [ForeignKey("ReportStoreId")]
        [InverseProperty("ReportGroupReport")]
        public virtual ReportStore ReportStore { get; set; }
    }
    }