// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Yashil.Common.Core.Interfaces;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Yashil.Core.Entities
{
[Table("ReportConnectionString", Schema = "rpt")]
    public partial class ReportConnectionString : IBaseEntity<int>
    {
        [Key]
        public int Id { get; set; }
        public int ReportId { get; set; }
        public int ConnectionStringId { get; set; }
        public int CreateBy { get; set; }
        public int? ModifyBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreationDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        public bool Deleted { get; set; }

        [ForeignKey("ConnectionStringId")]
        [InverseProperty("ReportConnectionString")]
        public virtual YashilConnectionString ConnectionString { get; set; }
        [ForeignKey("CreateBy")]
        [InverseProperty("ReportConnectionStringCreateByNavigation")]
        public virtual User CreateByNavigation { get; set; }
        [ForeignKey("ModifyBy")]
        [InverseProperty("ReportConnectionStringModifyByNavigation")]
        public virtual User ModifyByNavigation { get; set; }
        [ForeignKey("ReportId")]
        [InverseProperty("ReportConnectionString")]
        public virtual ReportStore Report { get; set; }
    }
    }