// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Yashil.Common.Core.Interfaces;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Yashil.Core.Entities
{
[Table("ReportStore", Schema = "rpt")]
    public partial class ReportStore : IBaseEntity<int>
    {
        public ReportStore()
        {
            ReportConnectionString = new HashSet<ReportConnectionString>();
            ReportGroupReport = new HashSet<ReportGroupReport>();
            RoleReport = new HashSet<RoleReport>();
            UserReport = new HashSet<UserReport>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(300)]
        public string Title { get; set; }
        public byte[] ReportFile { get; set; }
        [StringLength(50)]
        public string CssClass { get; set; }
        public byte[] Picture { get; set; }
        [StringLength(50)]
        public string Color { get; set; }
        public bool? Animation { get; set; }
        public string Description { get; set; }
        [StringLength(300)]
        public string ReportKey { get; set; }
        public string DesignString { get; set; }
        [StringLength(300)]
        public string ModuleKey { get; set; }
        public int CreateBy { get; set; }
        public int? ModifyBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreationDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        public int ApplicationId { get; set; }
        public int AccessLevelId { get; set; }
        public bool Deleted { get; set; }

        [ForeignKey("AccessLevelId")]
        [InverseProperty("ReportStore")]
        public virtual AccessLevel AccessLevel { get; set; }
        [ForeignKey("CreateBy")]
        [InverseProperty("ReportStoreCreateByNavigation")]
        public virtual User CreateByNavigation { get; set; }
        [ForeignKey("ModifyBy")]
        [InverseProperty("ReportStoreModifyByNavigation")]
        public virtual User ModifyByNavigation { get; set; }
        [InverseProperty("Report")]
        public virtual ICollection<ReportConnectionString> ReportConnectionString { get; set; }
        [InverseProperty("ReportStore")]
        public virtual ICollection<ReportGroupReport> ReportGroupReport { get; set; }
        [InverseProperty("Report")]
        public virtual ICollection<RoleReport> RoleReport { get; set; }
        [InverseProperty("Report")]
        public virtual ICollection<UserReport> UserReport { get; set; }
    }
    }