// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Yashil.Common.Core.Interfaces;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Yashil.Core.Entities
{
[Table("ResourceAppAction", Schema = "um")]
    public partial class ResourceAppAction : IBaseEntity<int>
    {
        public ResourceAppAction()
        {
            RoleResourceAction = new HashSet<RoleResourceAction>();
        }

        [Key]
        public int Id { get; set; }
        public int AppActionId { get; set; }
        public int ResourceId { get; set; }
        public int CreateBy { get; set; }
        public int? ModifyBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreationDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        public bool Deleted { get; set; }

        [ForeignKey("AppActionId")]
        [InverseProperty("ResourceAppAction")]
        public virtual AppAction AppAction { get; set; }
        [ForeignKey("ResourceId")]
        [InverseProperty("ResourceAppAction")]
        public virtual Resource Resource { get; set; }
        [InverseProperty("ResourceAction")]
        public virtual ICollection<RoleResourceAction> RoleResourceAction { get; set; }
    }
    }