// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Yashil.Common.Core.Interfaces;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Yashil.Core.Entities
{
[Table("Resource", Schema = "um")]
    public partial class Resource : IBaseEntity<int>
    {
        public Resource()
        {
            Menu = new HashSet<Menu>();
            ResourceAppAction = new HashSet<ResourceAppAction>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(300)]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        public int? Type { get; set; }
        public int CreateBy { get; set; }
        public int? ModifyBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreationDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        public bool Deleted { get; set; }

        [ForeignKey("CreateBy")]
        [InverseProperty("ResourceCreateByNavigation")]
        public virtual User CreateByNavigation { get; set; }
        [ForeignKey("ModifyBy")]
        [InverseProperty("ResourceModifyByNavigation")]
        public virtual User ModifyByNavigation { get; set; }
        [InverseProperty("Resource")]
        public virtual ICollection<Menu> Menu { get; set; }
        [InverseProperty("Resource")]
        public virtual ICollection<ResourceAppAction> ResourceAppAction { get; set; }
    }
    }