// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Yashil.Common.Core.Interfaces;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Yashil.Core.Entities
{
[Table("RoleResourceAction", Schema = "um")]
    public partial class RoleResourceAction : IBaseEntity<int>
    {
        [Key]
        public int Id { get; set; }
        public int ResourceActionId { get; set; }
        public int RoleId { get; set; }
        public int CreateBy { get; set; }
        public int? ModifyBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreationDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        public bool Deleted { get; set; }

        [ForeignKey("ResourceActionId")]
        [InverseProperty("RoleResourceAction")]
        public virtual ResourceAppAction ResourceAction { get; set; }
        [ForeignKey("RoleId")]
        [InverseProperty("RoleResourceAction")]
        public virtual Role Role { get; set; }
    }
    }