// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Yashil.Common.Core.Interfaces;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Yashil.Core.Entities
{
[Table("RoleReport", Schema = "rpt")]
    public partial class RoleReport : IBaseEntity<int>
    {
        [Key]
        public int Id { get; set; }
        public int RoleId { get; set; }
        public int ReportId { get; set; }
        public int CreateBy { get; set; }
        public int? ModifyBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreationDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        public bool Deleted { get; set; }

        [ForeignKey("CreateBy")]
        [InverseProperty("RoleReportCreateByNavigation")]
        public virtual User CreateByNavigation { get; set; }
        [ForeignKey("ModifyBy")]
        [InverseProperty("RoleReportModifyByNavigation")]
        public virtual User ModifyByNavigation { get; set; }
        [ForeignKey("ReportId")]
        [InverseProperty("RoleReport")]
        public virtual ReportStore Report { get; set; }
        [ForeignKey("RoleId")]
        [InverseProperty("RoleReport")]
        public virtual Role Role { get; set; }
    }
    }