// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Yashil.Common.Core.Interfaces;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Yashil.Core.Entities
{
[Table("RoleDashboard", Schema = "dash")]
    public partial class RoleDashboard : IBaseEntity<int>
    {
        [Key]
        public int Id { get; set; }
        public int RoleId { get; set; }
        public int DashboardId { get; set; }
        public int CreateBy { get; set; }
        public int? ModifyBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreationDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        public int? ApplicationId { get; set; }
        public bool Deleted { get; set; }

        [ForeignKey("CreateBy")]
        [InverseProperty("RoleDashboardCreateByNavigation")]
        public virtual User CreateByNavigation { get; set; }
        [ForeignKey("DashboardId")]
        [InverseProperty("RoleDashboard")]
        public virtual DashboardStore Dashboard { get; set; }
        [ForeignKey("ModifyBy")]
        [InverseProperty("RoleDashboardModifyByNavigation")]
        public virtual User ModifyByNavigation { get; set; }
        [ForeignKey("RoleId")]
        [InverseProperty("RoleDashboard")]
        public virtual Role Role { get; set; }
    }
    }