// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Yashil.Common.Core.Interfaces;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Yashil.Core.Entities
{
[Table("Role", Schema = "um")]
    public partial class Role : IBaseEntity<int>
    {
        public Role()
        {
            RoleDashboard = new HashSet<RoleDashboard>();
            RoleReport = new HashSet<RoleReport>();
            RoleResourceAction = new HashSet<RoleResourceAction>();
            UserRole = new HashSet<UserRole>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Title { get; set; }
        public string Description { get; set; }
        [Required]
        public bool? IsActive { get; set; }
        public int CreateBy { get; set; }
        public int? ModifyBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreationDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        public int ApplicationId { get; set; }
        public bool Deleted { get; set; }

        [ForeignKey("ApplicationId")]
        [InverseProperty("Role")]
        public virtual Application Application { get; set; }
        [ForeignKey("CreateBy")]
        [InverseProperty("RoleCreateByNavigation")]
        public virtual User CreateByNavigation { get; set; }
        [ForeignKey("ModifyBy")]
        [InverseProperty("RoleModifyByNavigation")]
        public virtual User ModifyByNavigation { get; set; }
        [InverseProperty("Role")]
        public virtual ICollection<RoleDashboard> RoleDashboard { get; set; }
        [InverseProperty("Role")]
        public virtual ICollection<RoleReport> RoleReport { get; set; }
        [InverseProperty("Role")]
        public virtual ICollection<RoleResourceAction> RoleResourceAction { get; set; }
        [InverseProperty("Role")]
        public virtual ICollection<UserRole> UserRole { get; set; }
    }
    }