// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Yashil.Common.Core.Interfaces;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Yashil.Core.Entities
{
[Table("User", Schema = "um")]
    public partial class User : IBaseEntity<int>, IApplicationBasedEntity
    {
        public User()
        {
            AccessLevelCreateByNavigation = new HashSet<AccessLevel>();
            AccessLevelModifyByNavigation = new HashSet<AccessLevel>();
            AppActionCreateByNavigation = new HashSet<AppAction>();
            AppActionModifyByNavigation = new HashSet<AppAction>();
            AppConfigCreateByNavigation = new HashSet<AppConfig>();
            AppConfigModifyByNavigation = new HashSet<AppConfig>();
            ApplicationCreateByNavigation = new HashSet<Application>();
            ApplicationModifyByNavigation = new HashSet<Application>();
            DashboardConnectionStringCreateByNavigation = new HashSet<DashboardConnectionString>();
            DashboardConnectionStringModifyByNavigation = new HashSet<DashboardConnectionString>();
            DashboardGroupDashboardCreateByNavigation = new HashSet<DashboardGroupDashboard>();
            DashboardGroupDashboardModifyByNavigation = new HashSet<DashboardGroupDashboard>();
            DashboardStoreCreateByNavigation = new HashSet<DashboardStore>();
            DashboardStoreModifyByNavigation = new HashSet<DashboardStore>();
            MenuCreateByNavigation = new HashSet<Menu>();
            MenuModifyByNavigation = new HashSet<Menu>();
            OrganizationCreateByNavigation = new HashSet<Organization>();
            OrganizationModifyByNavigation = new HashSet<Organization>();
            ReportConnectionStringCreateByNavigation = new HashSet<ReportConnectionString>();
            ReportConnectionStringModifyByNavigation = new HashSet<ReportConnectionString>();
            ReportGroupReportCreateByNavigation = new HashSet<ReportGroupReport>();
            ReportGroupReportModifyByNavigation = new HashSet<ReportGroupReport>();
            ReportStoreCreateByNavigation = new HashSet<ReportStore>();
            ReportStoreModifyByNavigation = new HashSet<ReportStore>();
            ResourceCreateByNavigation = new HashSet<Resource>();
            ResourceModifyByNavigation = new HashSet<Resource>();
            RoleCreateByNavigation = new HashSet<Role>();
            RoleDashboardCreateByNavigation = new HashSet<RoleDashboard>();
            RoleDashboardModifyByNavigation = new HashSet<RoleDashboard>();
            RoleModifyByNavigation = new HashSet<Role>();
            RoleReportCreateByNavigation = new HashSet<RoleReport>();
            RoleReportModifyByNavigation = new HashSet<RoleReport>();
            UserDashboardCreateByNavigation = new HashSet<UserDashboard>();
            UserDashboardModifyByNavigation = new HashSet<UserDashboard>();
            UserDashboardUser = new HashSet<UserDashboard>();
            UserReportCreateByNavigation = new HashSet<UserReport>();
            UserReportModifyByNavigation = new HashSet<UserReport>();
            UserReportUser = new HashSet<UserReport>();
            UserRoleCreateByNavigation = new HashSet<UserRole>();
            UserRoleModifyByNavigation = new HashSet<UserRole>();
            UserRoleUser = new HashSet<UserRole>();
            YashilDataProviderCreateByNavigation = new HashSet<YashilDataProvider>();
            YashilDataProviderModifyByNavigation = new HashSet<YashilDataProvider>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(200)]
        public string UserName { get; set; }
        [Required]
        [StringLength(200)]
        public string FirstName { get; set; }
        [Required]
        [StringLength(400)]
        public string LastName { get; set; }
        [StringLength(10)]
        public string NationalCode { get; set; }
        [StringLength(300)]
        public string Email { get; set; }
        [Required]
        [MaxLength(400)]
        public byte[] Password { get; set; }
        [Required]
        public bool? IsActive { get; set; }
        public int? MobileNumber { get; set; }
        public int? OrganizationId { get; set; }
        [Required]
        [MaxLength(400)]
        public byte[] PasswordSalt { get; set; }
        public string Address { get; set; }
        public int CreateBy { get; set; }
        public int? ModifyBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreationDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        public int ApplicationId { get; set; }
        public int AccessLevelId { get; set; }
        public bool Deleted { get; set; }
        public int CreatorOrganizationId { get; set; }

        [ForeignKey("AccessLevelId")]
        [InverseProperty("User")]
        public virtual AccessLevel AccessLevel { get; set; }
        [ForeignKey("ApplicationId")]
        [InverseProperty("User")]
        public virtual Application Application { get; set; }
        [ForeignKey("CreatorOrganizationId")]
        [InverseProperty("UserCreatorOrganization")]
        public virtual Organization CreatorOrganization { get; set; }
        [ForeignKey("OrganizationId")]
        [InverseProperty("UserOrganization")]
        public virtual Organization Organization { get; set; }
        [InverseProperty("CreateByNavigation")]
        public virtual ICollection<AccessLevel> AccessLevelCreateByNavigation { get; set; }
        [InverseProperty("ModifyByNavigation")]
        public virtual ICollection<AccessLevel> AccessLevelModifyByNavigation { get; set; }
        [InverseProperty("CreateByNavigation")]
        public virtual ICollection<AppAction> AppActionCreateByNavigation { get; set; }
        [InverseProperty("ModifyByNavigation")]
        public virtual ICollection<AppAction> AppActionModifyByNavigation { get; set; }
        [InverseProperty("CreateByNavigation")]
        public virtual ICollection<AppConfig> AppConfigCreateByNavigation { get; set; }
        [InverseProperty("ModifyByNavigation")]
        public virtual ICollection<AppConfig> AppConfigModifyByNavigation { get; set; }
        [InverseProperty("CreateByNavigation")]
        public virtual ICollection<Application> ApplicationCreateByNavigation { get; set; }
        [InverseProperty("ModifyByNavigation")]
        public virtual ICollection<Application> ApplicationModifyByNavigation { get; set; }
        [InverseProperty("CreateByNavigation")]
        public virtual ICollection<DashboardConnectionString> DashboardConnectionStringCreateByNavigation { get; set; }
        [InverseProperty("ModifyByNavigation")]
        public virtual ICollection<DashboardConnectionString> DashboardConnectionStringModifyByNavigation { get; set; }
        [InverseProperty("CreateByNavigation")]
        public virtual ICollection<DashboardGroupDashboard> DashboardGroupDashboardCreateByNavigation { get; set; }
        [InverseProperty("ModifyByNavigation")]
        public virtual ICollection<DashboardGroupDashboard> DashboardGroupDashboardModifyByNavigation { get; set; }
        [InverseProperty("CreateByNavigation")]
        public virtual ICollection<DashboardStore> DashboardStoreCreateByNavigation { get; set; }
        [InverseProperty("ModifyByNavigation")]
        public virtual ICollection<DashboardStore> DashboardStoreModifyByNavigation { get; set; }
        [InverseProperty("CreateByNavigation")]
        public virtual ICollection<Menu> MenuCreateByNavigation { get; set; }
        [InverseProperty("ModifyByNavigation")]
        public virtual ICollection<Menu> MenuModifyByNavigation { get; set; }
        [InverseProperty("CreateByNavigation")]
        public virtual ICollection<Organization> OrganizationCreateByNavigation { get; set; }
        [InverseProperty("ModifyByNavigation")]
        public virtual ICollection<Organization> OrganizationModifyByNavigation { get; set; }
        [InverseProperty("CreateByNavigation")]
        public virtual ICollection<ReportConnectionString> ReportConnectionStringCreateByNavigation { get; set; }
        [InverseProperty("ModifyByNavigation")]
        public virtual ICollection<ReportConnectionString> ReportConnectionStringModifyByNavigation { get; set; }
        [InverseProperty("CreateByNavigation")]
        public virtual ICollection<ReportGroupReport> ReportGroupReportCreateByNavigation { get; set; }
        [InverseProperty("ModifyByNavigation")]
        public virtual ICollection<ReportGroupReport> ReportGroupReportModifyByNavigation { get; set; }
        [InverseProperty("CreateByNavigation")]
        public virtual ICollection<ReportStore> ReportStoreCreateByNavigation { get; set; }
        [InverseProperty("ModifyByNavigation")]
        public virtual ICollection<ReportStore> ReportStoreModifyByNavigation { get; set; }
        [InverseProperty("CreateByNavigation")]
        public virtual ICollection<Resource> ResourceCreateByNavigation { get; set; }
        [InverseProperty("ModifyByNavigation")]
        public virtual ICollection<Resource> ResourceModifyByNavigation { get; set; }
        [InverseProperty("CreateByNavigation")]
        public virtual ICollection<Role> RoleCreateByNavigation { get; set; }
        [InverseProperty("CreateByNavigation")]
        public virtual ICollection<RoleDashboard> RoleDashboardCreateByNavigation { get; set; }
        [InverseProperty("ModifyByNavigation")]
        public virtual ICollection<RoleDashboard> RoleDashboardModifyByNavigation { get; set; }
        [InverseProperty("ModifyByNavigation")]
        public virtual ICollection<Role> RoleModifyByNavigation { get; set; }
        [InverseProperty("CreateByNavigation")]
        public virtual ICollection<RoleReport> RoleReportCreateByNavigation { get; set; }
        [InverseProperty("ModifyByNavigation")]
        public virtual ICollection<RoleReport> RoleReportModifyByNavigation { get; set; }
        [InverseProperty("CreateByNavigation")]
        public virtual ICollection<UserDashboard> UserDashboardCreateByNavigation { get; set; }
        [InverseProperty("ModifyByNavigation")]
        public virtual ICollection<UserDashboard> UserDashboardModifyByNavigation { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<UserDashboard> UserDashboardUser { get; set; }
        [InverseProperty("CreateByNavigation")]
        public virtual ICollection<UserReport> UserReportCreateByNavigation { get; set; }
        [InverseProperty("ModifyByNavigation")]
        public virtual ICollection<UserReport> UserReportModifyByNavigation { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<UserReport> UserReportUser { get; set; }
        [InverseProperty("CreateByNavigation")]
        public virtual ICollection<UserRole> UserRoleCreateByNavigation { get; set; }
        [InverseProperty("ModifyByNavigation")]
        public virtual ICollection<UserRole> UserRoleModifyByNavigation { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<UserRole> UserRoleUser { get; set; }
        [InverseProperty("CreateByNavigation")]
        public virtual ICollection<YashilDataProvider> YashilDataProviderCreateByNavigation { get; set; }
        [InverseProperty("ModifyByNavigation")]
        public virtual ICollection<YashilDataProvider> YashilDataProviderModifyByNavigation { get; set; }
    }
    }