// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Yashil.Common.Core.Interfaces;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Yashil.Core.Entities
{
[Table("UserDashboard", Schema = "dash")]
    public partial class UserDashboard : IBaseEntity<int>
    {
        [Key]
        public int Id { get; set; }
        public int UserId { get; set; }
        public int DashboardId { get; set; }
        public int CreateBy { get; set; }
        public int? ModifyBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreationDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        public int? ApplicationId { get; set; }
        public bool Deleted { get; set; }

        [ForeignKey("CreateBy")]
        [InverseProperty("UserDashboardCreateByNavigation")]
        public virtual User CreateByNavigation { get; set; }
        [ForeignKey("DashboardId")]
        [InverseProperty("UserDashboard")]
        public virtual DashboardStore Dashboard { get; set; }
        [ForeignKey("ModifyBy")]
        [InverseProperty("UserDashboardModifyByNavigation")]
        public virtual User ModifyByNavigation { get; set; }
        [ForeignKey("UserId")]
        [InverseProperty("UserDashboardUser")]
        public virtual User User { get; set; }
    }
    }