// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Yashil.Common.Core.Interfaces;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Yashil.Core.Entities
{
[Table("YashilDataProvider", Schema = "base")]
    public partial class YashilDataProvider : IBaseEntity<int>
    {
        public YashilDataProvider()
        {
            YashilConnectionString = new HashSet<YashilConnectionString>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string Title { get; set; }
        [Required]
        [StringLength(100)]
        public string BaseType { get; set; }
        public string Description { get; set; }
        [Required]
        public bool? IsActive { get; set; }
        public int CreateBy { get; set; }
        public int? ModifyBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreationDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        public bool Deleted { get; set; }
        public int? ApplicationId { get; set; }

        [ForeignKey("CreateBy")]
        [InverseProperty("YashilDataProviderCreateByNavigation")]
        public virtual User CreateByNavigation { get; set; }
        [ForeignKey("ModifyBy")]
        [InverseProperty("YashilDataProviderModifyByNavigation")]
        public virtual User ModifyByNavigation { get; set; }
        [InverseProperty("DataProvider")]
        public virtual ICollection<YashilConnectionString> YashilConnectionString { get; set; }
    }
    }