// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Yashil.Common.Core.Interfaces;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Yashil.Core.Entities
{
[Table("YashilConnectionString", Schema = "base")]
    public partial class YashilConnectionString : IBaseEntity<int>
    {
        public YashilConnectionString()
        {
            DashboardConnectionString = new HashSet<DashboardConnectionString>();
            ReportConnectionString = new HashSet<ReportConnectionString>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(200)]
        public string Title { get; set; }
        public int DataProviderId { get; set; }
        [Required]
        [StringLength(500)]
        public string ConnectionString { get; set; }
        public string Description { get; set; }
        [Required]
        public bool? IsActive { get; set; }
        public int CreateBy { get; set; }
        public int? ModifyBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreationDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        public bool Deleted { get; set; }
        public int? ApplicationId { get; set; }
        public int AccessLevelId { get; set; }

        [ForeignKey("CreateBy")]
        [InverseProperty("YashilConnectionStringCreateByNavigation")]
        public virtual User CreateByNavigation { get; set; }
        [ForeignKey("DataProviderId")]
        [InverseProperty("YashilConnectionString")]
        public virtual YashilDataProvider DataProvider { get; set; }
        [ForeignKey("ModifyBy")]
        [InverseProperty("YashilConnectionStringModifyByNavigation")]
        public virtual User ModifyByNavigation { get; set; }
        [InverseProperty("ConnectionString")]
        public virtual ICollection<DashboardConnectionString> DashboardConnectionString { get; set; }
        [InverseProperty("ConnectionString")]
        public virtual ICollection<ReportConnectionString> ReportConnectionString { get; set; }
    }
    }